version: '3.8'
services:
    php-apache-environment:
        container_name: php-apache4
        build:
            context: ./php
            dockerfile: Dockerfile
        depends_on:
            - db4
        volumes:
            - ./php/src:/var/www/html/
        ports:
            - 8007:80
    db4:
        container_name: db4
        image: mysql:5
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: MYSQL_ROOT_PASSWORD
            MYSQL_DATABASE: MYSQL_DATABASE
            MYSQL_USER: MYSQL_USER
            MYSQL_PASSWORD: MYSQL_PASSWORD
        ports:
            - "9907:3306"
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        ports:
             - '8087:80'
        restart: always
        environment:
            PMA_HOST: db4
            UPLOAD_LIMIT: 200M
        depends_on:
                  - db4                